
--***How to Setup a vehicle_names.lua for Custom Addon Vehicles *****
	Create a vehicle_names.lua & past the below Code
function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	--AddTextEntry('SPAWN_NAME_HERE', 'VEHICLE_NAME_HERE')
	--AddTextEntry('f350', '2013 Ford F350')
	AddTextEntry('i8','BMW I8'),
	AddTextEntry('mgt','Ford Mustang 2020'),
	AddTextEntry('vantage','Aston Martin'),
	AddTextEntry('astraj','Chevrolet Astra J'),
	AddTextEntry('jetta','Volkswagen Jetta'),
	AddTextEntry('cooperworks','Mini Cooper'),
	AddTextEntry('volt2','Chevrolet Volt'),
	AddTextEntry('cu2','Honda Accord'),
	AddTextEntry('civic','Honda Civic 99'),
	AddTextEntry('crv','Honda CRV'),
	AddTextEntry('s2k','Honda S2000'),
	AddTextEntry('gsf','Lexus GSF'),
	AddTextEntry('benzc32','Mercedes Benz C32 AMG 2004'),
	AddTextEntry('nisaltima','Nissan Altima'),
	AddTextEntry('camv50','Toyota Camry'),
	AddTextEntry('prius','Toyota Prius'),
	AddTextEntry('mk7','Volkswagen Golf GTI'),
	AddTextEntry('rs7','Audi RS7'),
	AddTextEntry('s5','Audi S5'),
	AddTextEntry('r8ppi','Audi R8'),
	AddTextEntry('bcgt','Bentley Continental'),
	AddTextEntry('m5e60','BMW M5 E60'),
	AddTextEntry('m6f13','BMW M6 F13'),
	AddTextEntry('z4alchemist','BMW Z4 Alchemist'),
	AddTextEntry('c7','Corvete C7'),
	AddTextEntry('gmcyd','GMC Yukon'),
	AddTextEntry('srt6','JEEP Grand Cherokee SRT8'),
	AddTextEntry('urus','Lamborghini Urus'),
	AddTextEntry('evo9','Lancer Evolution IX'),
	AddTextEntry('ev10','Lancer Evolution X'),
	AddTextEntry('rx7veilside','Mazda RX7 Drift KING Edition'),
	AddTextEntry('a45amg','Mercedes Benz A45 AMG'),
	AddTextEntry('gl63','Mercedes Benz GL63 AMG'),
	AddTextEntry('cls2015','Mercedes Benz CLS63 AMG'),
	AddTextEntry('370z'',Nissan 370z'),
	AddTextEntry('gtr','Nissan GTR'),
	AddTextEntry('skyline','Nissan SkylineGTR'),
	AddTextEntry('pcs18','Porsche Cayenne'),
	AddTextEntry('spyker''Spyker C8 Spyder'),
	AddTextEntry('dbs','Aston Martin DBS'),
	AddTextEntry('bdivo','Bugatti Divo'),
	AddTextEntry('488','Ferarri 488 GTB'),
	AddTextEntry('f812','Ferrari 812 SuperFast'),
	AddTextEntry('aperta','Ferrari LaFerrari Aperta'),
	AddTextEntry('mig','Ferrari Enzo'),
	AddTextEntry('gt17','Ford GT'),
	AddTextEntry('cx75','Jaguar C-X75'),
	AddTextEntry('lp770','Lamborghini Centenario'),
	AddTextEntry('lamtmc','Lamborghini Tierzo'),
	AddTextEntry('720s','McLaren 720s'),
	AddTextEntry('p1','McLaren P1'),
	AddTextEntry('mvisiongt','Mercedes Benz AMG GT'),
	AddTextEntry('c981','Porsche Cayman'),
	AddTextEntry('moss','Mercedes SLR McLaren STIRLING MOSS'),
	AddTextEntry('vulcan','Aston Martin Vulcan'),
	AddTextEntry('chevelle1970','Chevrolet Chevelle SS 1970'),
	AddTextEntry('69charger','Dodge Charger 69'),
	AddTextEntry('charger','Dodge Charger 70'),
	AddTextEntry('firebird','Pontiac Firebird 70'),
	AddTextEntry('ram2500','Dodge RAM 2500'),
	AddTextEntry('20f250','Ford F250'),
	AddTextEntry('18f350','Ford F350'),
	AddTextEntry('mercxclass','Mercedes Benz X-Class'),
	AddTextEntry('titan17','Nissan TITAN WARRIOR'),
	AddTextEntry('amarok','Volkswagen AMAROK'),
	AddTextEntry('bs17','BMWS1000RR'),
	AddTextEntry('hcbr17','Honda CBR1000'),
	AddTextEntry('h2carb','Kawasaki Ninja H2R'),
	AddTextEntry('r1','Yamaha YZF-R1'),
	AddTextEntry('r6','Yamaha YZF-R6'),
	AddTextEntry('tmax','Yamaha T-Max530')
end)
